# Generated by Django 3.0.2 on 2020-02-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='img',
            field=models.ImageField(upload_to='None'),
        ),
    ]
