# Generated by Django 3.0.2 on 2020-02-15 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_auto_20200215_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
