# Generated by Django 3.0.2 on 2020-02-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_auto_20200216_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
